title: Chon Kemp
description: Level Designer / Programmer

collections:
  projects:
    output: true
    permalink: /projects/:path/
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project
      nav_section: portfolio